PYTHON = python3

attack:
	@pip install numpy
	@pip install pandas
	@pip install pexpect
	@pip install pyfinite
	@${PYTHON} Plaintext_Generator.py
	@${PYTHON} Ciphertext_Generator.py
	@${PYTHON} Find_Keys.py
	@${PYTHON} Decrypt.py

